<a href="https://colab.research.google.com/github/namoshi/colab/blob/master/block_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

from numpy.linalg import inv


In [2]:
a = np.array([[1., 2.,3], [0., 1., 0.], [0, 0, 2]])
print(a)

[[1. 2. 3.]
 [0. 1. 0.]
 [0. 0. 2.]]


In [3]:
ainv = inv(a)
print(ainv)

[[ 1.  -2.  -1.5]
 [ 0.   1.   0. ]
 [ 0.   0.   0.5]]
