<a href="https://colab.research.google.com/github/namoshi/colab/blob/master/Hilbert_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Hirbelt 行列の固有値，固有ベクトル

In [9]:
import numpy as np
from numpy.linalg import eig

H = np.zeros((3,3))

for i in range(3):
  for j in range(3):
    H[i, j] = 1.0 / ((i+1) + (j+1) - 1.0)

print(H)

[L, E] = eig(H)

print('Eigen Values\n', L)
print('Eigen Vectors\n', E)


[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
Eigen Values
 [1.40831893 0.12232707 0.00268734]
Eigen Vectors
 [[ 0.82704493  0.54744843  0.12765933]
 [ 0.4598639  -0.52829024 -0.71374689]
 [ 0.32329844 -0.64900666  0.68867153]]
