<a href="https://colab.research.google.com/github/namoshi/colab/blob/master/iris_mlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torchvision.datasets as dsets
import torchvision.transforms as transforms



In [68]:
data = load_iris()
X = data.data
Y = data.target
Name = data.target_names

print('X', X.shape)
# print('Y', Y)
# print('Name', Name)

# normalize the X 
ss = StandardScaler()

X = ss.fit_transform(X)
print(X)

train_dataset = X.astype(np.float32)
#train_dataset.dtype = 'float32'
print(train_dataset.shape)

# set data loader
train_loader = torch.utils.data.DataLoader(
      dataset=train_dataset,  # データセットの指定
      batch_size=10,  # ミニバッチの指定
      shuffle=True,  # シャッフルするかどうかの指定
      num_workers=2)  # コアの数

X (150, 4)
[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -

In [69]:
# Linear Multi Layer Perceptron Network
class MLP (nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(4, 2)   
        self.fc2 = nn.Linear(2, 4)
        
    def forward(self, x):
        y = self.fc1(x)
        z = self.fc2(y)
        return z
 

In [70]:
# select device
device = 'cuda' if torch.cuda.is_available() else 'cpu'
net = MLP().to(device)
 
# optimizing
criterion = nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9, weight_decay=0.001)


In [71]:
###  training
print ('training start ...')
num_epochs = 50   
 
# initialize list for plot graph after training
train_loss_list = []

for epoch in range(num_epochs):
    # initialize each epoch
    train_loss = 0
    
    # ======== train_mode ======
    net.train()
    for i, xx in enumerate(train_loader):
#      print('i=',i)
#      print(xx)

      xx.to(device)
      optimizer.zero_grad()
      outputs = net(xx)
      loss = criterion(outputs, xx)
      train_loss += loss.item()
      loss.backward()
      optimizer.step()
      avg_train_loss = train_loss / len(train_loader.dataset)
    # print log
    print ('Epoch [{}/{}], Loss: {loss:.4f}' 
                   .format(epoch+1, num_epochs, i+1, loss=avg_train_loss))

training start ...
Epoch [1/50], Loss: 0.1259
Epoch [2/50], Loss: 0.1133
Epoch [3/50], Loss: 0.1008
Epoch [4/50], Loss: 0.0903
Epoch [5/50], Loss: 0.0808
Epoch [6/50], Loss: 0.0725
Epoch [7/50], Loss: 0.0648
Epoch [8/50], Loss: 0.0573
Epoch [9/50], Loss: 0.0504
Epoch [10/50], Loss: 0.0445
Epoch [11/50], Loss: 0.0391
Epoch [12/50], Loss: 0.0346
Epoch [13/50], Loss: 0.0308
Epoch [14/50], Loss: 0.0277
Epoch [15/50], Loss: 0.0250
Epoch [16/50], Loss: 0.0228
Epoch [17/50], Loss: 0.0209
Epoch [18/50], Loss: 0.0192
Epoch [19/50], Loss: 0.0178
Epoch [20/50], Loss: 0.0165
Epoch [21/50], Loss: 0.0153
Epoch [22/50], Loss: 0.0143
Epoch [23/50], Loss: 0.0133
Epoch [24/50], Loss: 0.0124
Epoch [25/50], Loss: 0.0117
Epoch [26/50], Loss: 0.0109
Epoch [27/50], Loss: 0.0103
Epoch [28/50], Loss: 0.0097
Epoch [29/50], Loss: 0.0091
Epoch [30/50], Loss: 0.0086
Epoch [31/50], Loss: 0.0082
Epoch [32/50], Loss: 0.0077
Epoch [33/50], Loss: 0.0074
Epoch [34/50], Loss: 0.0071
Epoch [35/50], Loss: 0.0068
Epoch [36/