<a href="https://colab.research.google.com/github/namoshi/colab/blob/master/linalg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## sympy を用いた線形代数

In [0]:
import sympy as sym

行列の宣言

In [2]:
A = sym.Matrix([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


   ”ｓｙｍｐｙ．Matrix” をnumpy.arrayに変換

In [3]:
A_n = sym.matrix2numpy(A)
print(A_n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


零行列

In [4]:
Zero = sym.Matrix.zeros(2, 3)
print(Zero)

Matrix([[0, 0, 0], [0, 0, 0]])


単位行列

In [5]:
I = sym.Matrix.eye(3,3)
print(I)

Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


対角行列

In [6]:
D = sym.Matrix.diag(1,2,3)
print(D)

Matrix([[1, 0, 0], [0, 2, 0], [0, 0, 3]])


In [7]:
print(A)
print(A[1,2])
print(A[0,0])
print(A[5])

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
6
1
6


In [8]:
B=sym.Matrix([[7,8,9],[4,5,6],[1,2,3]])
print(A)
print(B)
print(A * B)

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Matrix([[7, 8, 9], [4, 5, 6], [1, 2, 3]])
Matrix([[18, 24, 30], [54, 69, 84], [90, 114, 138]])


行列の簡約化（Raw Echelon Form)

In [9]:
print("A={}".format(A))
(G, Pv) = A.rref()
print("G={}".format(G))

A=Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
G=Matrix([[1, 0, -1], [0, 1, 2], [0, 0, 0]])


行列のランク

In [12]:
print(A.rank())
print(B.rank())
print((A * B - I).rank())

2
2
3


行列の逆行列

In [13]:
C=A * B - I
Cinv = C.inv()
print(Cinv)
print(C * Cinv)

Matrix([[-65/137, 33/137, -6/137], [81/274, -371/548, 48/137], [9/137, 111/274, -35/137]])
Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


### numpy, scipyを用いて線形代数

LU分解
\begin{align*}
    A = P L U
\end{align*}

In [14]:
import numpy as np
from scipy import linalg
from scipy.linalg import lu

# pylint: disable=invalid-name

A = np.array([[1, 2, 2],
              [2, 5, 6],
              [3, 8, 12]])

print("LU decomposition (A = PLU): ")
print("A:\n", A)
P, L, U = lu(A)
print("P: \n", P)
print("L: \n", L)
print("U: \n", U)
print("PLU: \n", P @ L @ U)

LU decomposition (A = PLU): 
A:
 [[ 1  2  2]
 [ 2  5  6]
 [ 3  8 12]]
P: 
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L: 
 [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.66666667 0.5        1.        ]]
U: 
 [[ 3.          8.         12.        ]
 [ 0.         -0.66666667 -2.        ]
 [ 0.          0.         -1.        ]]
PLU: 
 [[ 1.  2.  2.]
 [ 2.  5.  6.]
 [ 3.  8. 12.]]


逆行列

In [18]:
#Finding Inverse
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
print("A\n", A)

#Finding Inverse
invA = linalg.inv(A)
print("Inverse of A\n", invA)

# check of the
AinvA = A.dot(invA)
print("A invA\n", AinvA)

A
 [[1 3 5]
 [2 5 1]
 [2 3 8]]
Inverse of A
 [[-1.48  0.36  0.88]
 [ 0.56  0.08 -0.36]
 [ 0.16 -0.12  0.04]]
A invA
 [[ 1.00000000e+00 -1.11022302e-16  4.85722573e-17]
 [ 3.05311332e-16  1.00000000e+00  7.63278329e-17]
 [ 2.22044605e-16 -1.11022302e-16  1.00000000e+00]]


連立方程式の解 by using scipy
\begin{align*}
    \begin{bmatrix} 3 & 2 & 0 \\ 1 & -1 & 0 \\ 0 & 5 & 1 \end{bmatrix} 
    \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} = 
    \begin{bmatrix} 2 \\ 4 \\ -1 \end{bmatrix}
\end{align*}

In [15]:
#importing the scipy and numpy packages
from scipy import linalg
import numpy as np

#Declaring the numpy arrays
A = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])

m, n = A.shape

print('m=', m, 'n=', n)

# Augmented matrx [A b]
Ab = np.column_stack((A, b))
print("[A b]\n", Ab)

rankA = np.linalg.matrix_rank(A)
rankAb = np.linalg.matrix_rank(Ab)

print("Rank A=", rankA, "Rank [A b]=", rankAb)

if (rankA != rankAb):
    print("There is no solution!!!")
elif (n != rankA):
    print("There is no uniqe solution\n")
else:
    
    # Determinant of A
    detA = linalg.det(A)
    print("Determinant is", detA)

    #Passing the values to the solve function
    x = linalg.solve(A, b)

    #printing the result array
    print("The solurion is ", x)

    # A x
    print("A x =", A.dot(x))


m= 3 n= 3
[A b]
 [[ 3  2  0  2]
 [ 1 -1  0  4]
 [ 0  5  1 -1]]
Rank A= 3 Rank [A b]= 3
Determinant is -5.0
The solurion is  [ 2. -2.  9.]
A x = [ 2.  4. -1.]


固有値と固有ベクトル

In [21]:
# Eigenvalues and eigenvectors
import numpy as np
from scipy import linalg
A = np.array([[1, 2, 3], [3, 4, 3], [2, 1, 2]])
L, V = linalg.eig(A)
print("Eigne Values\n", L)   # eigenvalues
print("Eigen Vectors\n", V)

Eigne Values
 [ 6.93632273+0.j -1.16928575+0.j  1.23296302+0.j]
Eigen Vectors
 [[-0.45300009 -0.85454658  0.19208333]
 [-0.82007503  0.22398865 -0.80960671]
 [-0.34966823  0.46859281  0.55465391]]


特異値分解（SVD)

In [31]:
# Singular Value Decomposition

A = np.array([[1, 2,], [3, 4], [2, 1]])

print("A\n", A)

S, D, V = linalg.svd(A) 

print("S\n", S)
print("V\n", V)
print("D\n", D)

# Initialize `M` and `N`
M,N = A.shape
print("M=", M, "N=", N)

# Construct sigma matrix in SVD
Sig = linalg.diagsvd(D, M, N)
print("SIg", Sig)

print("S D V\n", np.dot(S.dot(Sig), V))

A
 [[1 2]
 [3 4]
 [2 1]]
S
 [[-0.37540137 -0.4485299  -0.81110711]
 [-0.85852835 -0.16151458  0.48666426]
 [-0.3492891   0.87905288 -0.32444284]]
V
 [[-0.62701799 -0.77900477]
 [ 0.77900477 -0.62701799]]
D
 [5.82051023 1.05908482]
M= 3 N= 2
SIg [[5.82051023 0.        ]
 [0.         1.05908482]
 [0.         0.        ]]
S D V
 [[1. 2.]
 [3. 4.]
 [2. 1.]]
