<a href="https://colab.research.google.com/github/namoshi/colab/blob/master/othogonal_projection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 直交射影と直交補空間への射影

\begin{align*}
 P = X(X^TX)^{-1}X^T
\end{align*}

\begin{align*}
 I-P = I - X(X^T X)^{-1} X^T
\end{align*}

特異値分解との関係




In [38]:
import numpy as np

X = np.random.rand(7,3)

print(X)

S, D, Vh = np.linalg.svd(X)

print(S.shape, D.shape, Vh.shape)

L = len(D)
print('S\n', S)
print('D\n', D)
print('V\n', Vh)
SD = np.dot(S[:,:L], np.diag(D))
print(SD)
print(np.dot(SD, Vh))

P = np.dot(Vh.T, Vh)

print('P\n', P)

IP = np.eye(len(P)) - P

print('P X[1,:]\n', np.dot(P, X[1,:].T))

print('(I-P) X[1,:]\n', np.dot(IP, X[1,:].T))


[[0.29184476 0.6633715  0.61464842]
 [0.73233805 0.44264379 0.09865343]
 [0.34299452 0.74507263 0.1749611 ]
 [0.95038031 0.35495641 0.6586681 ]
 [0.69001892 0.4989379  0.68748997]
 [0.08926747 0.91796071 0.92860923]
 [0.53836998 0.07294145 0.86643238]]
(7, 7) (3,) (3, 3)
S
 [[-0.36251073 -0.27866747 -0.01890284 -0.36260993 -0.40643488 -0.5983737
  -0.36857393]
 [-0.27733209  0.3273312  -0.54139833 -0.4720423  -0.20561773  0.50257497
  -0.07172764]
 [-0.27972039 -0.21308879 -0.5506128   0.2171225   0.05158801 -0.28902641
   0.6632009 ]
 [-0.44661739  0.47603342  0.01087008  0.67346755 -0.23815327 -0.04506434
  -0.24799316]
 [-0.42988883  0.15572992  0.02850334 -0.17832715  0.83610204 -0.159601
  -0.18382511]
 [-0.45447844 -0.66840106  0.17745753  0.17287739  0.0033027   0.52712665
  -0.08624491]
 [-0.35015316  0.26864901  0.60904375 -0.28862124 -0.1845974   0.02156999
   0.56253222]]
D
 [2.52324031 0.92296737 0.74119074]
V
 [[-0.53701193 -0.54984941 -0.63975293]
 [ 0.79107524 -0.5916082