<a href="https://colab.research.google.com/github/namoshi/colab/blob/master/quasi_diagonal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Quasi Diagonal Natural Gradient



In [3]:
import numpy as np

F = np.array([[2, 1, 2, 3], [1, 3, 0, 0], [2, 0, 2, 0], [3, 0, 0, 1]])

print(F)

[[2 1 2 3]
 [1 3 0 0]
 [2 0 2 0]
 [3 0 0 1]]


In [4]:
from numpy.linalg import inv

Finv = inv(F)

print(Finv)

[[-0.10714286  0.03571429  0.10714286  0.32142857]
 [ 0.03571429  0.32142857 -0.03571429 -0.10714286]
 [ 0.10714286 -0.03571429  0.39285714 -0.32142857]
 [ 0.32142857 -0.10714286 -0.32142857  0.03571429]]


In [12]:
print(F[1, 1])

denomi = F[0, 0]
fdf = 0.0
for i in range(3):
  print(i)
  fdf += F[0, i+1] * F[0, i+1] / F[i+1, i+1]

denomi -= fdf

print('(1,2)=', F[0, 1] * F[0, 2]/(F[1, 1] * F[2, 2]) / denomi)
print('(2,3)=', F[0, 2] * F[0, 3]/(F[2, 2] * F[3, 3]) / denomi)

3
0
1
2
(1,2)= -0.03571428571428571
(2,3)= -0.3214285714285714


非対角要素の計算は合っている！