<a href="https://colab.research.google.com/github/namoshi/colab/blob/master/raw_echelon_form.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

def find_raw_echelon_form(matrix):
    m, n = matrix.shape
    lead = 0  # リーディングエッジの列

    for r in range(m):
        if lead >= n:
            break

        i = r
        while matrix[i, lead] == 0:
            i += 1
            if i == m:
                i = r
                lead += 1
                if n == lead:
                    return matrix

        matrix[[i, r]] = matrix[[r, i]]

        if matrix[r, lead] != 0:
            matrix[r] = matrix[r] / matrix[r, lead]

        for i in range(m):
            if i != r:
                matrix[i] = matrix[i] - matrix[i, lead] * matrix[r]

        lead += 1

    return matrix



Raw Echelon Form:
[[ 1  0 -1]
 [ 0  1  2]
 [ 0  0  0]]


In [14]:
# サンプル行列を作成
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

echelon_form = find_raw_echelon_form(A)
print("Raw Echelon Form:")
print(echelon_form)


Raw Echelon Form:
[[ 1  0 -1]
 [ 0  1  2]
 [ 0  0  0]]
