<a href="https://colab.research.google.com/github/namoshi/colab/blob/master/Reduced_Raw_Echelon_Form.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def find_reduced_row_echelon_form(matrix):
    m, n = matrix.shape
    lead = 0  # リーディングエッジの列

    for r in range(m):
        if lead >= n:
            break

        i = r
        while matrix[i, lead] == 0:
            i += 1
            if i == m:
                i = r
                lead += 1
                if n == lead:
                    return matrix

        matrix[[i, r]] = matrix[[r, i]]

        if matrix[r, lead] != 0:
            matrix[r] = matrix[r] / matrix[r, lead]

        for i in range(m):
            if i != r:
                factor = matrix[i, lead]
                matrix[i] = matrix[i] - factor * matrix[r]

        lead += 1

    return matrix



Reduced Row Echelon Form:
[[ 1  0 -1]
 [ 0  1  2]
 [ 0  0  0]]


In [2]:
# サンプル行列を作成
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

reduced_row_echelon_form = find_reduced_row_echelon_form(A)
print("Reduced Row Echelon Form:")
print(reduced_row_echelon_form)


Reduced Row Echelon Form:
[[ 1  0 -1]
 [ 0  1  2]
 [ 0  0  0]]


In [4]:
A = np.array([[1, 3, 2, 3],
              [-1, -2, 1, 1],
              [2, 5, -1, 0],
              [0, 1, 1, 2]])

reduced_row_echelon_form = find_reduced_row_echelon_form(A)
print("Reduced Row Echelon Form:")
print(reduced_row_echelon_form)


Reduced Row Echelon Form:
[[ 1  0  0 -2]
 [ 0  1  0  1]
 [ 0  0  1  1]
 [ 0  0  0  0]]
